### PR TITLE
FIXED: Incorrect line for AppKernel.php

### PR DESCRIPTION
**Pull request by hipio**
I messed up a few months ago and stated that `new DealerDirect\ShortUUIDBundle\ORM\Id\UUIDGenerator()` should be included in `AppKernel.php`, but this is the file will be used for generating the UUID's itself and thus does not contain the bundle definition. 

Funny that nobody noticed this before. ;)

### CODE REVIEW

**Comment by hipio** [comment]
Failing test is not related to my change: 
>The command "~/.composer/vendor/bin/phpmd ./src text phpmd.xml" exited with 0.
>$ ~/.composer/vendor/bin/security-checker -n security:check
>                                                                                       
>  An error occurred: gnutls_handshake() failed: A TLS fatal alert has been received.`

**Comment by mjrider** [comment]
build error might be related to https://github.com/travis-ci/travis-ci/issues/6339

**Comment by hipio** [comment]
@mjrider that looks like it just might be the reason, yes. Let's hope it get's resolved quickly. 😄

**Comment by Marascon** [comment]
Hello Hipio,

Thanks for your PR. 
As you might have noticed we have been quite busy last week and did not get around your pr's

We will handle them as soon as possible

**Comment by Potherca** [comment]
> Funny that nobody noticed this before. ;)

I guess people are using common sense instead of reading the docs. :stuck_out_tongue:

**Comment by Marascon** [comment]
As i see everything is in working order, and Travis is still prone to be failing. i will ask an administrator to merge this.

@Potherca you see any chance of merging this?

**Pull request merged**
